export const FETCH_FAILURE = "FETCH_FAILURE";

export const FETCH_ALL_UNITS_REQUEST = "FETCH_ALL_UNITS_REQUEST";
export const FETCH_ALL_UNITS_SUCCESS = "FETCH_ALL_UNITS_SUCCESS";

export const GET_UNIT_REQUEST = "GET_UNIT_REQUEST";
export const GET_UNIT_SUCCESS = "GET_UNIT_SUCCESS";

export const FILTER_BY_FILTERS_REQUEST = "FILTER_BY_FILTERS_REQUEST";
export const FILTER_BY_FILTERS_SUCCESS = "FILTER_BY_FOLTERS_SUCCESS";
