export const FETCH_TODO_REQUEST = "FETCH_TODO_REQUEST";
export const FETCH_TODO_SUCCESS = "FETCH_TODO_SUCCESS";
export const FETCH_TODO_FAILURE = "FETCH_TODO_FAILURE";

export const FETCH_ALL_UNITS_REQUEST = "FETCH_ALL_UNITS_REQUEST";
export const FETCH_ALL_UNITS_SUCCESS = "FETCH_ALL_UNITS_SUCCESS";
export const GET_UNIT_REQUEST = "GET_UNIT_REQUEST";
export const GET_UNIT_SUCCESS = "GET_UNIT_SUCCESS";
export const FILTER_BY_AGE_REQUEST = "FILTER_BY_AGE_REQUEST";
export const FILTER_BY_AGE_SUCCESS = "FILTER_BY_AGE_SUCCESS";
export const FILTER_BY_FILTERS_REQUEST = "FILTER_BY_FILTERS_REQUEST";
export const FILTER_BY_FILTERS_SUCCESS = "FILTER_BY_FOLTERS_SUCCESS";
export const FETCH_UNIT_REQUEST = "FETCH_UNIT_REQUEST";
export const FETCH_UNIT_SUCCESS = "FETCH_UNIT_SUCCESS";

//TODO remove trash from this file
